take2/config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  get '/signup', to: 'stores#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  post '/stores', to: 'stores#create'
  post "/account/token_reset", to: "store_owners#token_reset"
  
  get '/account/:id', to: 'stores#show', as: 'account'

  get '/receipts', to: 'receipts#show', as: 'receipts'
  post '/receipts', to: 'receipts#create'

  # this route is necessary for using respond_with
  get '/receipt/:id', to: 'receipts#show', as: 'receipt'

  get '/passwd_reset', to: 'stores#passwd_reset', as: 'passwd_reset'

end

take2/app/models/api_token.rb
class ApiToken < ActiveRecord::Base

  validates :hex_value, uniqueness: true

  belongs_to :store

end

take2/app/models/receipt.rb
class Receipt < ActiveRecord::Base

  belongs_to :store

end

take2/app/models/store.rb
class Store < ActiveRecord::Base

  has_secure_password

  # need a workaround for this line or it'll spit out an error
  # SyntaxError: /app/models/store.rb:7: syntax error, unexpected '\n', expecting =>
  # before_validation :on => :create, :gen_api_token

  # validations
  validates :api_token,
            :uniqueness => true

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, confirmation: true

  # associations
  has_many :receipts, dependent: :destroy
  has_one :api_token, dependent: :destroy

  # returns store or false
  def self.confirm(params)
    store = Store.find_by(email: params[:email])
    store.try(:authenticate, params[:password])
  end

   def gen_api_token
      token = SecureRandom.uuid

      # run simple validation
      until StoreOwner.find_by(api_token: token).nil?
        token = SecureRandom.uuid
      end

      self.api_token = token
    end

end

take2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  include SessionsHelper

end

take2/app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController

  before_action :require_token
  rescue_from ActiveRecord::RecordNotFound, with: :bad_token
  respond_to :html, :json

    def index
    @receipts = current_store.receipts
    respond_to do |f|
      f.json { render json: @receipts }
    end
  end

  #
  # GET /receipts.json
  #
  def show
    if current_store.api_token
      @receipts = current_store.receipts
      respond_with @receipts
    else
      # unauthorized
      render json: { status:"error",
                       mesg:"Invalid API token" }, status: 401
    end
  end

  #
  # POST /receipts.json
  #
  def create
    if current_store.api_token
      @receipt = current_store.Receipt.create receipt_params
      # Make sure there's a receipt_path in routes.rb
      # The responder will look for a receipt_path even though it's
      # not actually redirecting (as in the case of JSON response)
      respond_with @receipt
      # equivalent to:
      # respond_to do |format|
      #   if @receipt.save
      #     format.json { render json: @receipt, location: receipt_path }
      #   else
      #     format.json { render json: @receipt.errors, status: :unprocessable_entity }
      #   end
      # end
    else
      # unauthorized
      render json: { status:"error",
                       mesg:"Invalid API token" }, status: 401
    end
  end


  protected

    def bad_token(e)
      render json: { status: 401,  errors: e.message }, status: 401
    end


  private

  def validate_api_token
    @api_token = ApiToken.find_by hex_value:params[:api_token]
  end

  def receipt_params
    # permit all receipt attributes
    # maybe not secure, but not typing everying out
    # TODO: a better way?
    params.require(:receipt).permit!
  end

end

take2/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :failed_login
  #
  # GET /login
  #
  def new
  end

  #
  # POST /sessions
  #
  def create
    if params[:email].present? && params[:password].present?
      # email and password entered, ok
      if Store.find_by(email:params[:email])
        # found a user, ok
        @store = Store.confirm(email:params[:email], password:params[:password])
        if @store
          # user authorized, ok
          login @store
          redirect_to account_path(@store)
        else
          # bad password
          # display the login page again
          render :new
        end
      else
        # user not found
        # have them sign up
        redirect_to signup_path
      end
    else
      # incomplete login fields
      render :new
    end
  end

  #
  # GET /logout
  #
  def destroy
    logout
    redirect_to root_path
  end

end

take2/app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index
  end

end

take2/app/controllers/stores_controller.rb
class StoresController < ApplicationController

  before_action :require_login, only: [:show, :reset_token]
  rescue_from ActiveRecord::RecordInvalid, with: :invalid_signup

  #
  # GET /signup
  #
  def new
    @store = Store.new
  end

  #
  # GET /account/:id
  #
  def show
    @store = Store.find params[:id]
  end

  #
  # POST /stores
  #
  def create
    @store = Store.new store_params
    if @store.save
      # line 27 => to change
      @store.gen_api_token
      login @store
      redirect_to account_path @store
    else
      render :new
    end
  end

  def passwd_reset
    # can only get here through login form
    # can't go here if logged in
  end

  # login required for this
  def token_reset
    current_owner.gen_api_token
    current_owner.save
    redirect_to "/account"
  end

  protected

    def invalid_signup(e)
      flash[:error]= e.message
      redirect_to "/signup"
    end

  private

  def store_params
    params.require(:store).permit(:name, :email, :email_confirmation, :password, :password_confirmation)
  end

  def assign_api_token store
    # TODO: handle uniqueness validation failure
    @api_token = ApiToken.create(store_id:store.id, hex_value:SecureRandom.hex)
  end

end

take2/app/helpers/application_helper.rb
module ApplicationHelper
end

take2/app/helpers/receipts_helper.rb
module ReceiptsHelper
end

take2/app/helpers/sessions_helper.rb
module SessionsHelper

  def login(store)
    session[:store_id] = store.id
    @current_store = store
  end

  def current_store
    @current_store ||= Store.find_by_id(session[:store_id])
  end

  def logged_in?
    !current_store.nil?
  end

  def require_login
    if !logged_in?
      redirect_to "/login"
    end
  end

  def logout
    @current_store = session[:store_id] = nil
  end

end

take2/app/helpers/site_helper.rb
module SiteHelper
end

take2/app/helpers/stores_helper.rb
module StoresHelper
end

take2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JsonApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-static-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse_button">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Store It</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <% if current_store %>
        <div class="collapse navbar-collapse" id="collpase_button">
          <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_store.email %><span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="<%= account_path(current_store) %>">Account Profile</a></li>
                  <li class="divider"></li>
                  <li><a href="<%= logout_path %>">Logout</a></li>
                </ul>
              </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      <% end %>
    </div><!-- /.container-fluid -->
  </nav>

<div class='container'>

  <%= yield %>

</div>

</body>
</html>

take2/app/views/receipts/create.html.erb
<h1>Receipts#create</h1>
<p>Find me in app/views/receipts/create.html.erb</p>

take2/app/views/receipts/show.html.erb
<h1>Receipts#show</h1>
<p>Find me in app/views/receipts/show.html.erb</p>

take2/app/views/site/index.html.erb
  <div class='col-md-3 text-right'>
    <%= link_to 'Signup', signup_path, class: "btn btn-lg btn-primary" %>
  </div>
  <div class='col-md-9 text-left'>
    <%= link_to 'Login', login_path, class: "btn btn-lg btn-primary" %>
  </div>

take2/app/views/stores/edit.html.erb
<h1>Stores#edit</h1>
<p>Find me in app/views/stores/edit.html.erb</p>

take2/app/views/stores/index.html.erb
<h1>Stores#index</h1>
<p>Find me in app/views/stores/index.html.erb</p>

take2/app/views/stores/new.html.erb
<div class='col-md-6'>
  <div class='well'>
    <div class='row'>
      <div class='col-md-4 text-right'>
        <h3>New Store</h3>
      </div>
    </div>
    <br>
    <%= form_for(@store) do |f| %>
      <div class='row'>
        <div class='col-md-11 col-md-offset-1'>
          <% if @store.errors.any? %>
            <p>Please fix the following
              <%= pluralize(@store.errors.count, "error") %>
              with your registration: </p>
            <ul>
              <% @store.errors.full_messages.each do |mesg| %>
                <li><%= mesg %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
      </div><br>
      <div class='row'>
        <div class='col-md-4 text-right'>
          <%= f.label "Name: " %>
        </div>
        <div class='col-md-7'>
          <%= f.text_field(:name, { autofocus: "true" }) %>
        </div>
      </div>
      <br>
      <div class='row'>
        <div class='col-md-4 text-right'>
          <%= f.label "Email: " %>
        </div>
        <div class='col-md-7'>
          <%= f.text_field(:email) %>
        </div>
      </div>
      <br>
      <div class='row'>
        <div class='col-md-4 text-right'>
          <%= f.label "Confirm email: " %>
        </div>
        <div class='col-md-7'>
          <%= f.text_field(:email_confirmation) %>
        </div>
      </div>
      <br>
      <div class='row'>
        <div class='col-md-4 text-right'>
          <%= f.label "Password: " %>
        </div>
        <div class='col-md-7'>
          <%= f.password_field(:password) %>
        </div>
      </div>
      <br>
      <div class='row'>
        <div class='col-md-4 text-right'>
          <%= f.label "Confirm password: " %>
        </div>
        <div class='col-md-7'>
          <%= f.password_field(:password_confirmation) %>
        </div>
      </div>
      <br>
      <div class='row'>
        <div class='col-md-11 text-right'>
          <%= f.submit("Sign up", class: "btn btn-primary") %>
          <br><br>
          <p>Already registered?&nbsp&nbsp<span><%= link_to('Log in here', login_path) %></span></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

take2/app/views/stores/passwd_reset.html.erb
<div class='col-md-5'>
  <div class='well'>
    <div class='row'>
      <div class='col-md-7 text-right'>
        <h3>Reset Password</h3>
      </div>
    </div>
    <br>
    <%= form_tag(sessions_path) do %>
      <div class='row'>
        <div class='col-md-3 text-right'>
          <%= label_tag(:email) %>
        </div>
        <div class='col-md-8'>
          <%= text_field_tag(:email) %>
        </div>
      </div>
      <br>
      <div class='row'>
        <div class='col-md-11 text-right'>
          <%= submit_tag("Submit", class: "btn btn-primary") %>
          <br><br>
        </div>
      </div>
      <div class='row'>
        <div class='col-md-11 text-right'>
          <%= link_to('Sign up', signup_path) %> | <%= link_to('Log in', login_path) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

take2/app/views/stores/show.html.erb
<div class='col-md-6'>
  <div class='well'>
    <div class='row'>
      <div class='col-md-4 text-right'>
        <h3>Account Info</h3>
      </div>
    </div>
    <br>
    <div class='row'>
      <div class='col-md-4 text-right'>
        Store name:
      </div>
      <div class='col-md-7'>
        <%= @store.name %>
      </div>
    </div>
    <br>
    <div class='row'>
      <div class='col-md-4 text-right'>
        Email:
      </div>
      <div class='col-md-7'>
        <%= @store.email %>
      </div>
    </div>
    <br>
    <div class='row'>
      <div class='col-md-4 text-right'>
        API Token:
      </div>
      <div class='col-md-7'>
        <%= @store.api_token.hex_value %>
      </div>
    </div>
    <br>
  </div>    <!-- well -->
</div>